.gflows/libs/configuration.lib.yml, .gflows/libs/job_unit_test.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
Add functionality to define docker run parameters.
Added new optional array field `image_run_args` to sections.
During the docker run, each item would be passed as an argument to `docker run`. 
Now works for unit tests image only.
Can be used in scenarios when we have a single unit test image but like to split different groups of tests on different jobs
=> Add docker run parameters

.gflows/libs/configuration.lib.yml, .gflows/libs/steps.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
Add functionality to control if image build job should push docker build cache or not. 
Add optional boolean setting `cache_push` to all docker-related section. Default value is true. If it is set to false, build cache would not be pushed to configured destination.
Useful in scenarios when the produced cache cannot be reused and we like to save on cache push time, which can be long. For example, when we build nuget packages with versioned dlls and using `repository` cache with `cache_mode=max` to consume main service-produced cache
=> Allow to disable or enable cache load and push

.gflows/libs/job_integration_test.lib.yml, github-sample/workflows/build-publish.yml
Add support for multiple projects with acceptance tests 
`cucumber_result_filename` may contain a wildcard specifying several cucumber results files to upload to behave.pro
=> Multiple projects for acceptance tests

.gflows/libs/job_scan_code_net.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
By default scan_code_net job only needs "version" job , if  scan_code_net job is required to run after certain docker  images to be built, cache_from attr can be used. 
Example: 
```yml
scan_code_net:
name: Sonar Code
slug: scan_code_net
#optional
cache_from:
- covergo/auth
- covergo/auth-test-unit
```
=> Added option to allow scan code job to extend needs

.gflows/libs/build_publish_steps.lib.yml, .gflows/libs/job_integration_test.lib.yml, github-sample/workflows/build-publish.yml
Services are tagged with  candidate-app_version , this should be reflected to the docker image tag in the  docker-compose file so that integration tests that use service images do not encounter to image not found errors
See BE-458
=> Append candidate- to service tags in docker-composes file

.gflows/libs/job_version.lib.yml, github-sample/workflows/build-publish.yml
In our current CI flow, we add 'latest' docker tag for the images we push to the master or main branches, but master branch images are deployed to dev environment, not prod. Ideally, we should mark images deployed to prod environment with latest tag, and mark images that are deployed to the dev env. with the branch name
see: BE-410
=> fix: set latest docker tag for only tagged commits where tag starts with 'v'

.gflows/libs/job_integration_test.lib.yml, .gflows/libs/steps.lib.yml, github-sample/workflows/build-publish.yml
docker-diagnose cannot collect docker-compose logs due to missing -p arg. docker-diagnose script v1.8 should fix it
=> fix(ci diagnostic logs):  Diagnostic logs are missing from the uploaded CI asset

.gflows/config.yml, .gflows/libs/build_publish_steps.lib.yml, .gflows/libs/configuration.lib.yml, .gflows/libs/job_docker_build.lib.yml, .gflows/libs/job_docker_publish_alicloud.lib.yml, .gflows/libs/job_docker_publish_github.lib.yml, .gflows/libs/steps.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
This PR updates the build-publish workflow to store docker image digest as output and sign the docker image with cosign after publishing to container registry.
=> [BE-528] - Updates Workflow to Sign Docker Image After Publish

.gflows/libs/job_docker_publish_alicloud.lib.yml, .gflows/libs/job_docker_publish_github.lib.yml, github-sample/workflows/build-publish.yml
`docker_image_ghcr_tags` and `docker_image_ali_cloud_tags` contain multiple comma separated docker image url when merged to master or tagged. This causes image signing command to fail. This PR aims to fix it by using the [versioned docker image url](https://github.com/CoverGo/build-publish-net-workflow/blob/ce3f341f5af6bb5c13fb1aadd89d7ef8085227a4/github-sample/workflows/build-publish.yml#L54) for both registries.
=> [BE-528] - Fixes container image signing fails on master

.gflows/libs/steps.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
Currently, we are setting docker build args within the gflow template. We want to expand this and accept custom docker build-args  to be passed to the components. This will allow services to pass custom build-args to the workflow. It is also optional.
=> feat: Custom build args support for docker build

.gflows/gflowspkg.json, .gflows/libs/job_update_leaderboard.lib.yml, .gflows/workflows/build-publish/build-publish.template.yml
BE-740
This PR adds a job that creates a leaderboard of contributors. A poll was started in the `#backend` channel (https://covergo.slack.com/archives/G013PMH64T0/p1676279723004669) and as of now the majority (4 vs 2) voted to add the gamification.
The job uploads `leaderboard.md` file to GitHub Actions Artifacts.
=> Add `update leaderboard` job

.gflows/gflowspkg.json, .gflows/libs/job_scan_code.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, .gflows/workflows/build-publish/build-publish.template.yml, README.md, github-sample/workflows/build-publish.yml
This PR enables support for SonarCloud analysis in non-dotnet repos. It's supposed to be used to enable SonarCloud quality gates in BE-owned JavaScript repos like [data-migrations](https://github.com/CoverGo/saas-data-migrations) and Scripts-js.
Can be used like this:
After applying gflows transformation it results in the following GitHub action job:
=> BE-774 Implement SonarCloud analysis for non-dotnet repos

.gflows/libs/configuration.lib.yml
This function `get_sonar_project` is used on the file `job_scan_code_net.lib.yml` but the implementation of the function is missing so the gflows failed to generate when we try to override the project key.
=> fix: failed when override the sonar project key

.gflows/libs/job_integration_test.lib.yml, github-sample/workflows/build-publish.yml
Trying to fix such errors:
```
start to read cucumber logs using path ./TestResults/FeatureData.json
found cucumber report /home/runner/work/Policies/Policies/TestResults/FeatureData.json
/home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/reportReader.js:5
.map(fileReport => globalFileInformation(fileReport))
^
TypeError: report.map is not a function
at Object.module.exports.globalInformation (/home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/reportReader.js:5:10)
at /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/index.js:75:48
```
BE-806
=> fix: update cucumber report

.gflows/libs/steps.lib.yml, github-sample/workflows/build-publish.yml
We can drop this hard code once `ubuntu-latest` image will feature buildx 0.11.2+
=> BE-770 fix: use buildx 0.11.2 to fix failing builds

.gflows/gflowspkg.json
an issue appeared after tagging with release version and trying to use it in Gateway service:
```
root@DESKTOP-VEKT32C:/mnt/c/Projects/Gateway# gflows update help
error .github/workflows/build-publish.yml (from build-publish-net/workflows/build-publish)
► - cannot load job_scan_image.lib.yml: Expected to find file 'job_scan_image.lib.yml' (hint: only files included via -f flag are available)
identical .github/workflows/workflows-check.yml (from workflow-check/workflows/workflows-check)
identical .github/workflows/helm-chart.yml (from helm-chart/workflows/helm-chart)
```
looks like it's mandatory to add the lib to the package list bundle
=> added a new lib to the bundle

.gflows/libs/build_publish_steps.lib.yml, .gflows/libs/integration-tests-legacy-steps.lib.yml, .gflows/libs/job_build_nuget.lib.yml, github-sample/workflows/build-publish.yml
Upgrade upload-artifact action to version 4
Error message
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: [Deprecation notice: v1 and v2 of the artifact actions · GitHub Changelog](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)
```
=> CH-11556 Upgrade version of upload-artifact action

.gflows/libs/build_publish_steps.lib.yml, .gflows/libs/integration-tests-legacy-steps.lib.yml, .gflows/libs/job_build_nuget.lib.yml, .gflows/libs/job_publish_nuget.lib.yml, .gflows/libs/job_scan_code_net.lib.yml, github-sample/workflows/build-publish.yml
- Upgrade download-artifact action to version 4.
- Set include-hidden-files: true for upload-artifact action.
=> CH-11556 Upgrade version of download-artifact action

.gflows/libs/build_publish_steps.lib.yml, github-sample/workflows/build-publish.yml
Added the following to avoid rate limit:
- **github_retries: 3:** Sets the number of retries for GitHub API requests to 3, which is lower than the default of 10, helping you balance between retries and rate limit considerations.
- **comment_mode: off:** Disables comments on pull requests to reduce the number of API calls, which is critical in avoiding hitting rate limits.
- **compare_to_earlier_commit: false**: Disables comparison of test results with previous commits, reducing unnecessary API requests. 
- **check_run: false**: Disables publishing the results as a GitHub check run, which further reduces API usage.
- **check_run_annotations: none**: Disables annotations in the check run, further minimizing API requests.
=> CH-9368: Added retry if rate limit

.gflows/libs/build_publish_steps.lib.yml, .gflows/libs/job_docker_publish_alicloud.lib.yml, .gflows/libs/job_docker_publish_github.lib.yml, .gflows/libs/job_publish_nuget.lib.yml, .gflows/libs/job_scan_code_net.lib.yml, .gflows/workflow-configuration/build-publish/settings.yml, github-sample/workflows/build-publish.yml
Some steps does not run properly on self-hosted runners, issues are related to dotnet installation and docker config file location. This PR fixes the issues making it work on any runner. 
`docker-config-path` is used only in push action so it's added there with the default option valid for Github-managed runners. The path could be different for self-hosted runners because of the user, currently we use root but we may redefine it later.
=> added an option to specify the docker_config_path for custom runners

.gflows/libs/steps.lib.yml, github-sample/workflows/build-publish.yml
We found out that Docker Hub introduces [pull limitations starting 1st of March 2025](https://docs.docker.com/docker-hub/usage/) which could impact the build-publish workflow. We already experience this problem with self-hosted runners so we can use AWS ECR official image instead. The image works, you can see it [here](https://github.com/CoverGo/Policies/actions/runs/13181922470/job/36794643516).
=> use Covergo ghcr.io image for buildx

.gflows/libs/integration-tests-legacy-steps.lib.yml
Sample failing runs due to deprecated:
- https://github.com/CoverGo/Products/actions/runs/14484963142/job/40628879699?pr=524#step:7:16
- https://github.com/CoverGo/Templates/actions/runs/14486535387/job/40633343510?pr=237
Successful run on products:
- https://github.com/CoverGo/Products/actions/runs/14485183028/job/40629492145
=> fix: remove deprecated cache action

.gflows/libs/steps.lib.yml, github-sample/workflows/build-publish.yml
This pull request updates the token configuration for build and publish workflows by adding new environment variables for enterprise and npm tokens. These changes ensure the workflows can access additional secrets required for specific operations.
* [`.gflows/libs/steps.lib.yml`](diffhunk://#diff-948c33842360bed653b37e9efa94b5ec10f40cd98076213a7fe14f469e0d0157R120-R121): Added `FORMKIT_ENTERPRISE_TOKEN` and `COVERGO_NPM_TOKEN` as build arguments to support enterprise and npm-related operations.
* [`github-sample/workflows/build-publish.yml`](diffhunk://#diff-7b56bcf408a66ee9dddd84e1063f9c7d341ecc193e8c7baaf110f6ea333b4b40R386-R387): Added `FORMKIT_ENTERPRISE_TOKEN` and `COVERGO_NPM_TOKEN` as environment variables in the `jobs` section to make these tokens accessible during the build and …
=> CH-22814 update build-args to have npm tokens
